### ISSUE TITLE
Error when installing the module on 2.1.14

### ISSUE THREAD

**Issue by hieunguyenzzz** [cloudinary/cloudinary_magento2#39]
When I install the module on my site on 2.1.14 which following instruction

```
composer require cloudinary/cloudinary-magento2
php bin/magento maintenance:enable
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
php bin/magento maintenance:disable
php bin/magento cache:flush
```

it ended up with this error 
```
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Validator\ValidatorInterface in /home/jamest75/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /home/jamest75/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /home/jamest75/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /home/jamest75/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(232): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'protocolValidat...', 'Cloudinary\\Clou...')
#3 /home/jamest75/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Cloudinary\\Cl in /home/jamest75/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

I have cleared cache before running the script, also remove var/di

is the module support Magento version 2.1.14 ?

**Comment by pniel-cohen** [comment]
@hieunguyenzzz 
Please try to upgrade your Cloudinary module to the latest version (1.9.9), it should solve your issue.

**Comment by hieunguyenzzz** [comment]
the module is no longer support 2.1.14 after upgrading 

![Screenshot from 2019-09-20 13-29-51](https://user-images.githubusercontent.com/24548582/65304791-b4293200-dbab-11e9-8032-270ff1fa1895.png)

**Comment by pniel-cohen** [comment]
@hieunguyenzzz , Thanks for letting us know.
A fix for that will be released soon.

**Comment by pniel-cohen** [comment]
@hieunguyenzzz
v1.10.0 contains a few fixes that should solve it for you.

**Comment by asisayag2** [comment]
@hieunguyenzzz, will be great if you could let us know if all goes well now. 
Thanks

**Comment by hieunguyenzzz** [comment]
after upgrading, I am getting this from admin when I try to edit product

![Screenshot from 2019-09-24 17-32-34](https://user-images.githubusercontent.com/24548582/65504514-5ff6b880-def1-11e9-8fb8-eab607b9f962.png)

**Comment by eyalktCloudinary** [comment]
@hieunguyenzzz Can you try to uninstall the module, run `composer clearcache`, and reinstall?

**Comment by hieunguyenzzz** [comment]
I have tried clear composer cache and get the module again

![Screenshot from 2019-09-28 10-15-54](https://user-images.githubusercontent.com/24548582/65810768-07693900-e1d9-11e9-9fb5-ff3843a054e1.png)

and then trigger all of this stuff

```
php bin/magento maintenance:enable
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
php bin/magento maintenance:disable
php bin/magento cache:flush
```

the issue is still persist 

![Screenshot from 2019-09-28 10-17-41](https://user-images.githubusercontent.com/24548582/65810779-40091280-e1d9-11e9-92b3-03274e2a1616.png)

**Comment by JamesMobelaris** [comment]
Can we have update on this please, this is urgent we have paid for month for a solution that isnt working

**Comment by eyalktCloudinary** [comment]
@JamesMobelaris The fix has been merged, you can now install it via the composer. I apologize for the delay in response.

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
